const DATA = {
    name: "Gabriel Renato",
    handle: "gabriel-santo",
    role: "Full Stack Developer",
    location: "São Paulo, BR",
    bio: "Crafting scalable web applications with a sharp eye for UX/UI. Bridging code and creativity — from React ecosystems to 3D art and game development.",
    stack: ["ReactJS", "TypeScript", "Node.js", "Python", "Figma", "Blender", "UE5"],
    email: "gabrielrntsanto@gmail.com",
    github: "https://github.com/biel-santo",
    linkedin: "https://www.linkedin.com/in/gabrielrsanto/",
    codeProjects: [
        {
            id: 1,
            title: "HMVM",
            type: "Institutional Interface",
            year: "2022",
            tech: ["HTML", "CSS3", "CMS"],
            desc: "Institutional web interface built and maintained for high-visibility platform.",
            url: "https://hmvm.com.br",
        },
        {
            id: 2,
            title: "Eco Semáforo",
            type: "Sustainability Platform",
            year: "2023",
            tech: ["HTML", "CSS3", "CMS"],
            desc: "Web platform with focus on environmental sustainability and smart signaling.",
            url: "https://ecosemaforo.com.br",
        },
        {
            id: 3,
            title: "Autome.md",
            type: "Developer Tool",
            year: "2026",
            tech: ["Next.js", "TypeScript", "Tailwind CSS"],
            desc: "README generator with templates, badge builder, and live dark mode preview. Built for devs who want professional docs fast.",
            url: "https://autome-md-nextjs.vercel.app/",
          },
          {
            id: 4,
            title: "Network Infrastructure",
            type: "Systems & Security",
            year: "2024",
            tech: ["IP Networks", "CFTV", "Linux"],
            desc: "IP device mapping, addressing and configuration for critical monitoring systems.",
          },
    ],
    artProjects: [
        {
            id: 1,
            title: "3D Character Studies",
            type: "3D Art / Blender",
            year: "2023",
            tech: ["Blender", "Substance Painter"],
            desc: "Character modeling and rendering explorations — form, light, and material.",
        },
        {
            id: 2,
            title: "Game Environment",
            type: "Unreal Engine 5",
            year: "2023",
            tech: ["UE5", "Blender", "Megascans"],
            desc: "Immersive environment built in UE5, focusing on atmosphere and lighting.",
        },
        {
            id: 3,
            title: "2D Motion & Graphic Design",
            type: "Animation / Design",
            year: "2022",
            tech: ["Adobe CC", "After Effects", "Illustrator"],
            desc: "Motion graphics and visual identity projects from SAGA design program.",
        },
        {
            id: 4,
            title: "UX/UI Prototyping",
            type: "Interface Design",
            year: "2023",
            tech: ["Figma", "Prototyping"],
            desc: "High-fidelity interface prototypes with emphasis on user experience and clarity.",
        },
    ],
    blog: [
        {
            id: 1,
            title: "Security-first mindset in full stack",
            date: "Mar 2026",
            tag: "Security",
            desc: "Lessons from an MBA in Cybersecurity applied to everyday web development.",
        },
        {
            id: 2,
            title: "On building things that last",
            date: "Feb 2025",
            tag: "Engineering",
            desc: "Thoughts on scalable architecture, technical debt, and writing code for the next developer.",
        },
        {
            id: 3,
            title: "When code meets canvas",
            date: "Jan 2024",
            tag: "Creative",
            desc: "How my background in 3D art and game dev shapes the way I think about frontend.",
        },
    ],
};

export default DATA;